---
- name: restart nova-compute
  service: name=nova-compute state=restarted
- name: restart openvswitch-switch
  service: name=openvswitch-switch state=restarted
- name: restart neutron-plugin-openvswitch-agent
  service: name=neutron-plugin-openvswitch-agent state=restarted
- name: restart neutron-l3-agent
  service: name=neutron-l3-agent state=restarted
- name: restart neutron-dhcp-agent
  service: name=neutron-dhcp-agent state=restarted
- name: restart neutron-metadata-agent
  service: name=neutron-metadata-agent state=restarted
- name: restart ceilometer-agent-compute
  service: name=ceilometer-agent-compute state=restarted
