---
- name: Test Echo Controller
  shell: echo hello world
- name: install the MySQL client and server packages, rabbitMQ and the Python library
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
    - mysql-server
    - rabbitmq-server

- name: install oslo package
  pip: name=oslo.rootwrap state=latest
- name: install openstack project clients
  pip: name=python-{{ item }}client state=latest
  with_items:
    - ceilometer
    - cinder
    - heat
    - keystone
    - neutron
    - swift
    - trove

- include: database.yml
- include: keystone.yml
- include: glance.yml
- include: nova.yml
- include: neutron.yml
- include: horize.yml
- include: cinder.yml
