---
- name: echo controller nova
  shell: echo hello controller nova
- name: Compute packages necessary for the controller node
  apt: name={{ item }} state=present
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
    - python-novaclient
    - python-oslo.rootwrap
- name: upload nova configuration file
  template: src=nova.conf dest=/etc/nova/nova.conf backup=yes
- name: restart nova-api
  service: name=nova-api state=restarted
- name: restart nova-cert
  service: name=nova-cert state=restarted
- name: restart nova-consoleauth
  service: name=nova-consoleauth state=restarted
- name: restart nova-scheduler
  service: name=nova-scheduler state=restarted
- name: restart nova-conductor
  service: name=nova-conductor state=restarted
- name: restart nova-novncproxy
  service: name=nova-novncproxy state=restarted
- name: try remove the nova sqllite db file
  shell: rm /var/lib/nova/nova.sqlite || touch nova.sqllite.db.removed
- name: synd nova database
  shell: su -s /bin/sh -c "nova-manage db sync" nova
