---
- name: ensure IP forward bit is activated
  sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes
- name: ensure IPv4 rp filter is deactivated
  sysctl: name=net.ipv4.conf.all.rp_filter value=0 state=present reload=yes
- name: ensure IPv4 default rp filter is deactivated
  sysctl: name=net.ipv4.conf.default.rp_filter value=0 state=present reload=yes

- name: install the Networking components
  apt: name={{ item }}
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent
    - openvswitch-datapath-dkms
    - neutron-l3-agent
    - neutron-dhcp-agent
- name: configure the Networking common components
  template: src=neutron.conf dest=/etc/neutron/neutron.conf backup=yes

- name: configure the Layer-3 (L3) agent
  template: src=l3_agent.ini dest=/etc/neutron/l3_agent.ini backup=yes

- name: configure the DHCP agent
  template: src=dhcp_agent.ini dest=/etc/neutron/dhcp_agent.ini backup=yes

- name: create or update dnsmasq-neutron.conf
  template: src=dnsmasq-neutron.conf dest=/etc/neutron/dnsmasq-neutron.conf

- name: killall dnsmasq process
  shell: killall dnsmasq || echo error

- name: configure the metadata agen
  template: src=metadata_agent.ini dest=/etc/neutron/metadata_agent.ini backup=yes

- name: configure the Modular Layer 2 (ML2) plug-in
  template: src=ml2_conf.ini dest=/etc/neutron/plugins/ml2/ml2_conf.ini backup=yes

- name: Restart the OVS service
  service: name=openvswitch-switch state=restarted

- name: add the integreation bridge
  openvswitch_bridge: bridge=br-int state=present

- name: add the external bridge
  openvswitch_bridge: bridge=br-ex state=present

- name: Add a port to the external bridge that connects to the physical external network interface
  openvswitch_port: bridge=br-ex port={{ INTERFACE_NAME }} state=present

- name: restart service
  shell: echo hello service
  notify:
    - restart neutron-plugin-openvswitch-agent
    - restart neutron-l3-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
