---
- name: ensure cinder-volume and lvm2 packages are installed
  apt: pkg={{ item }}
  with_items:
    - cinder-volume
    - lvm2

- name: ensure physical and group volume are created
  lvg: vg=cinder-volumes pvs={{ physical_device }} vg_options=--force

- name: upload cinder-volume configuration
  template: src=etc/cinder/cinder.conf dest=/etc/cinder/cinder.conf backup=yes
  notify:
    - resatrt cinder-volume
    - resatrt tgt
